In [1]:
import numpy as np

In [5]:
arr = np.array(range(1,10)).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# slicing

In [7]:
arr[:2] # eje 0 hasta la 2-- sin incluirla

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr[:2,1:] # eje 0 hasta 2 --sin incluirlo, eje 1 desde 1 -- incluido

array([[2, 3],
       [5, 6]])

In [13]:
arr[1,:2] # eje 0 solo pos 1, hasta 2 -- sin incluirlo

array([4, 5])

# filtros bool

In [19]:
arr < 6

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [20]:
arr[arr < 6]

array([1, 2, 3, 4, 5])

In [21]:
arr[arr > 6]

array([7, 8, 9])

# funciones universales

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [25]:
np.abs(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [27]:
np.add(arr,arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# funciones de agregacion

In [28]:
arr = np.random.randn(5,4)
arr

array([[ 5.49369443e-02,  1.05544895e+00, -1.70456686e-02,
         8.07966443e-01],
       [ 2.22864133e-01,  7.26002060e-01,  1.97474930e+00,
        -1.93602051e-01],
       [ 2.03163454e-03, -2.53590466e-02,  1.16292175e+00,
         2.36188810e+00],
       [ 6.41913059e-01, -1.75380323e-01, -1.91777413e+00,
        -1.78706430e-01],
       [-7.61761011e-02, -6.62462209e-01, -1.15174272e+00,
         1.17892698e-01]])

In [30]:
arr.shape, arr.ndim

((5, 4), 2)

In [32]:
arr.mean(), np.mean(arr)

(0.23651831973500959, 0.23651831973500959)

In [33]:
arr.sum()

4.730366394700192